# Generated by Django 5.1.1 on 2025-01-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsor_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
