# Generated by Django 5.1.1 on 2025-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_alter_user_sponsor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='fox', max_length=300),
            preserve_default=False,
        ),
    ]
