# Generated by Django 5.1.1 on 2025-01-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsor_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
