# Generated by Django 5.1.1 on 2025-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='Operateur',
            field=models.CharField(default='INCONNU', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='is_MTN',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='indirect_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
