# Generated by Django 5.1.1 on 2025-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_remove_withdrawal_operateur_remove_withdrawal_is_mtn_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="indirect_indirect_commission_percentage",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
