# Generated by Django 5.1.1 on 2025-01-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='notions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='presentation_video',
            field=models.FileField(blank=True, null=True, upload_to='formations/videos/'),
        ),
    ]
