# Generated by Django 5.1.1 on 2025-01-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0003_formation_notions_alter_formation_presentation_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='notation',
            field=models.FloatField(blank=True, default=4.5, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='participants_number',
            field=models.IntegerField(blank=True, default=2153, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duration',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='points',
            field=models.IntegerField(default=40),
        ),
    ]
