# Generated by Django 5.1.1 on 2025-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0004_formation_notation_formation_participants_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('development', 'Développement Personnel'), ('business', 'Business'), ('sales', 'Ventes'), ('tech', 'Technologie'), ('other', 'Autres')], default='other', max_length=60),
        ),
    ]
