# Generated by Django 5.1.1 on 2025-02-01 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0005_formation_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='telegramsubscription',
            old_name='subscription_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='telegramsubscription',
            name='phone_number',
            field=models.CharField(default='658866639', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramsubscription',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telegramsubscription',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscription', to='Edu.payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
