# Generated by Django 5.1.1 on 2025-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0006_alter_telegramsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
