# Generated by Django 5.1.1 on 2025-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0007_inscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
