# Generated by Django 5.1.1 on 2025-02-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0010_remove_footerinfo_telegram_alter_footerinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
