# Generated by Django 5.1.1 on 2025-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0011_footerinfo_telegram_alter_footerinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='telegram_canal',
            field=models.URLField(blank=True, null=True),
        ),
    ]
