# Generated by Django 5.1.1 on 2025-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0012_footerinfo_telegram_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscription',
            name='username',
            field=models.CharField(default='@aucun', max_length=100),
        ),
    ]
